### ISSUE TITLE
NMRrium does not show 1D spectra of linderazuele

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1012]
Dear all,

**Describe the bug**
Something went wrong with sample 10.57992/nmrxiv.p2.s273 , though I thought that I have checked this before I pressed the "publish" button (Btw: The other two, pulegon, carminic acid, are fine). All 2D NMR spectra are fine. All 1D NMR spectra are not displayed.

**To Reproduce**
1. Go to https://doi.org/10.57992/nmrxiv.p2.s273
2. Scroll down to spectra. 
3. Try to have a look on 1H, 13C and APT.
4. See nothing.

**Expected behavior**
Also show all 1D spectra.

**Additional context**
You could also unpublish the sample another time, so that I could try to reupload the data, if that might be helpfull.

Best,
Tillmann

**Comment by tilfischer** [comment]
I had a look on 2D data, then went to 13C (no spectrum) and to 1H (no spectrum) but got this error message:

```
Details
Cannot read properties of undefined (reading 'toFixed')

TypeError: Cannot read properties of undefined (reading 'toFixed')
    at getDecimalsCount (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60633:31955)
    at PeakAnnotationsTreeStyle (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60633:33328)
    at Xh (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:22071)
    at dj (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:3545)
    at cj (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:2674)
    at aj (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:2135)
    at Wk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:52714)
    at Vk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44159)
    at Uk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44080)
    at Jk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:43918)
    at Ok (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:39850)
    at Fk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:40754)
    at jg$1 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:3590)
    at https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:37966
```

**Comment by CS76** [comment]
Regenerated the NMRium JSON. Working now.

@hamed-musallam, can you check what is the issue here?

[S273_1D_issues.nmrium.json](https://github.com/NFDI4Chem/nmrxiv/files/13943086/S273_1D_issues.nmrium.json)
[S273_updated.nmrium.json](https://github.com/NFDI4Chem/nmrxiv/files/13943087/S273_updated.nmrium.json)

**Comment by tilfischer** [comment]
Spectra are shown now. Thank you!
