### ISSUE TITLE
challenges with some types of Bruker NMR data

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#981]
Dear all,

**Background**

A recent lead by example dataset has NMR data in Bruker format obtained with TopSpin 3.6. This NMR data worked seamlessly in nmrXiv with NMRium. To my knowledge TopSpin 3.6 by default automatically processed the FIDs in expno and saves the parameters and the processed spectra (procno) in the pdata folder. However, older version of TopSpin such as 3.2 do not automatically process FIDs, hence, there is not necessarily a pdata folder present with procno and processing parameters and spectra. The challenge NMR operators face is that they often cannot upgrade TopSpin to the newest version (currently TopSpin 4.3) for all spectrometers, as the newer version of TopSpin does not support older spectrometers. An overview is provided by Bruker [here](https://www.bruker.com/protected/en/services/software-downloads/nmr/pc/pc-topspin.html). Login is required to access that page. 

Additionally, there are setting in TopSpin on what is actually saved. The default setting is that it saves 1) the FID in expno, 2) the processing parameters and 3) the processed spectra (1i/1r for 1D NMR) in procno within pdata folder. It is also possibly to use setting in TopSpin to only save the FID or to only save the FID and the processing parameters but not the processed spectra. Some operators tend not to save the processing parameters and/or processed spectra or the data was obtained on an older spectrometer with TopSpin  3.2 and below without processing of the FID by the operator.

**Describe the bug**

Not all types of Bruker data with/without processed spectra (1i/1r) and with/without processing parameters can be uploaded to nmrXiv and processed with NMRium in nmrXiv.

**Tests**

I did some tests with the NMR data of Pulegone [published in RADAR4Chem](https://dx.doi.org/10.22000/785). 

1) The original NMR data has a pdata folder with procno with the processing parameters but without the processed spectra. If I select the sample after upload in step 2/3 and NMRium gave the error message ``Something went wrong.`` with that type of data.

```
Details
unreachable: Spectrum with id c37d46a8-7639-45ef-87d4-0da19d50fb39 not found

Error: unreachable: Spectrum with id c37d46a8-7639-45ef-87d4-0da19d50fb39 not found
    at assert$1 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:59982:41)
    at https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7350
    at Array.map (<anonymous>)
    at https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7221
    at Object.useMemo (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:29226)
    at react_production_min.useMemo (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:9:7237)
    at Viewer2D (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7195)
    at Xh (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:22071)
    at Wk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:48945)
    at Vk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44159)
    at Uk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44080)
    at Jk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:43918)
    at Ok (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:39850)
    at Hk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:38674)
    at V0 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:25:1729)
    at MessagePort.i1 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:25:2141)
```

2) For another test I uploaded the dataset without the pdata folder (and procno) i.e. as the data would have been saved in TopSpin with the setting set not to save processing parameters and processed spectra. This should be comparable to Bruker data obtained with TopSpin 3.2 and before and without any processing done by the operator. However, I could not proceed to step 2 but nmrXiv displayed ``Please upload spectral data to proceed``. In case I dropped the same type of data to NMRium directly, the 1D spectra were automatically processed, while not the 2D spectra. Btw: About a year ago NMRium also did not automatically process the 1D data [see this issue](https://github.com/cheminfo/nmrium/issues/2005).

3) I opened the NMR data with TopSpin 4.3. Automatic processing took place and the processed spectra were saved for each NMR experiment. I uploaded this to nmrXiv.
-> works! 

**Expected behavior**

Ingestion of all types of Bruker data by nmrXiv with or without pdata folder. If there is no pdata folder, FID should be automatically processed to show the processed spectrum. If there is a pdata folder with processing parameter but without processed spectra, processing based on the processing parameters should take place and the processed spectrum should be shown to the user.

Best,
Tillmann

**Comment by CS76** [comment]
Dear Tillmann,

Thank you so much for the valuable insights. We will include those in the documentation site and hint the submitters during the upload process.

1) Issue with displaying spectra
> unreachable: Spectrum with id c37d46a8-7639-45ef-87d4-0da19d50fb39 not found

This is primarily due to outdated NMRium - nmrXiv JSON and could be resolved if we reset the spectra using the "reset" option. The loading screen might be blocking the user from resetting the data. We will deploy a fix soon to resolve this issue without resetting the spectra and make the reset option available when the spectra fail to load.

2) "pdata" folder requirement
> For another test I uploaded the dataset without the pdata folder (and procno) i.e. as the data would have been saved in TopSpin with the setting set not to save processing parameters and processed spectra. This should be comparable to Bruker data obtained with TopSpin 3.2 and before and without any processing done by the operator. However, I could not proceed to step 2 but nmrXiv displayed `Please upload spectral data to proceed`. In case I dropped the same type of data to NMRium directly, the 1D spectra were automatically processed, while not the 2D spectra. Btw: About a year ago NMRium also did not automatically process the 1D data [see this issue](https://github.com/cheminfo/nmrium/issues/2005).

nmrXiv explicitly looks for the pdata folder and hence it blocks the user from proceeding to step 2 if missing. If you think that we will have to enable submissions without "pdata" folder, we could make this optional. However at this stage we dont process the spectra completely.

> Ingestion of all types of Bruker data by nmrXiv with or without pdata folder. If there is no pdata folder, FID should be automatically processed to show the processed spectrum. If there is a pdata folder with processing parameter but without processed spectra, processing based on the processing parameters should take place and the processed spectrum should be shown to the user.

Done we will take this into consideration and make necessary changes to the validation.

**Comment by tilfischer** [comment]
Dear Chandu,

Thank you for your reply!

1. Issue with displaying spectra

I am wondering why there should be an outdated NMRium/nmrXiv JSON. I started and could reproduce the issue: Dashboard -> Upload -> + Create new -> drag and drop of NMR data in https://dx.doi.org/10.22000/785 (no processed spectra but processed parameters) -> Step 2/3 -> selected the sample -> Errror:

```
Details
unreachable: Spectrum with id e3374b89-42ab-4539-b38a-f1c6813d14f2 not found

Error: unreachable: Spectrum with id e3374b89-42ab-4539-b38a-f1c6813d14f2 not found
    at assert$1 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:59982:41)
    at https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7350
    at Array.map (<anonymous>)
    at https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7221
    at Object.useMemo (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:29226)
    at react_production_min.useMemo (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:9:7237)
    at Viewer2D (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:60482:7195)
    at Xh (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:38:22071)
    at Wk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:48945)
    at Vk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44159)
    at Uk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:44080)
    at Jk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:43918)
    at Ok (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:39850)
    at Hk (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:40:38674)
    at V0 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:25:1729)
    at MessagePort.i1 (https://nmrium.nmrxiv.org/assets/vendor-pQ64cooI.js:25:2141)
```
![Screenshot 2024-01-09 152647](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/2f9c6792-1ba2-46ac-b4d6-3881f09b8415)

Same problem, If I add a structure to the sample i.e. that does not make any difference. 

If data without pdata folder is not acceptable, then, this should be added to the documentation. I had a look, but couldn't find any clear statement on that.

NMRium and nmrXiv should at least accept data with a pdata folder with processing parameters but without processed spectra. 

Best,
Tillmann

**Comment by tilfischer** [comment]
Dear Chandu,

I had another look on this and got some imput from Varian NMR data. The Hygrophorones curated by Toni were recorded on an Agilent NMR Spectrometer* with VnmrJ, previously developed by Varian and now continued open source as [OpenVnmrJ](https://github.com/OpenVnmrJ/OpenVnmrJ). For this type of data, NMRium only display the FID but also does not eat the processing parameters in procpar file. Moreover, there is no option in VnmrJ to save processed spectra, as this is the case for Bruker data. Allover, Varian data is comparable to ``1.`` mentioned in the beginning of this issue as it has a FID and processing parameters (Bruker proc, Varian procpar). To not have the processed spectra is actually the more elegant solution, as this data can be obtained anyhow based on the FID and available processing parameters.

In one (long) sentence: nmrXiv should accept NMR data having the FID and the processing parameters but not the processed spectra and NMRium in nmrXiv should use the processing parameters to reprocess the FID and display the spectrum after processing to the users. 

NMRium does not use the proc and procpar but does an automated processing (currently) only for 1D data such as 1H and 13C by selecting own processing parameters. I agree that this is not an issue for nmrXiv but NMRium and I will open another issue at https://github.com/cheminfo/nmrium.

What remains for this issue? If I provide data of type ``1.`` (see top of this issue), NMRium accepts this and automated processing starts ignoring the procpar and proc but displaying the spectrum after processing to the user, while nmrXiv gives and error. 

Best,
Tillmann

*This Agilent spectrometer is actually younger then 10 years, so it will continue to produce data for at least another 10-15 years and there are many more Varian/Agilent spectrometers out there.

**Comment by tilfischer** [comment]
Tested ``1.`` again. Didn't get any errors anymore. Seems to be solved.

Test ``2.`` again. [NMRium ](https://www.nmrium.org/nmrium) accepts the Bruker folder without pdata, while nmrXiv does not. For https://www.nmrium.org/nmrium it is even sufficient to provide the fid and acqus file (fid and acqu does not work).

**Comment by NRayya** [comment]
Closed in favor of Accept Bruker data that doesn't have pdata folder #1188
